Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

 
  
  $provision_script= <<SCRIPT
   sudo apt-get install -y puppet
SCRIPT
   config.vm.provision :shell, :inline => $provision_script
   
   
   
  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "../manifests"
     puppet.manifest_file  = "base-hadoop.pp"
     puppet.module_path = "../modules"
  end


  config.vm.define :backup do |box|
    
    box.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_DOJO_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_DOJO_SECRET_ACCESS_KEY']
  	  aws.availability_zone = "eu-west-1a"
  	  aws.private_ip_address = '10.10.0.51'
  	  aws.region = 'eu-west-1'
  	  aws.security_groups = 'sg-db0dc0be'
  	  aws.subnet_id = 'subnet-4d64893a'
  	  aws.associate_public_ip = false
      aws.keypair_name = 'Lukas Test'

      aws.ami = "ami-8b6c96fc"
    
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/Users/cscarion/.ssh/LukasTest.pem"
      aws.tags = { "Name" => "Hadoop Backup Box"}
    
    end
  end
  
  config.vm.define :master do |box|
    
    box.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_DOJO_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_DOJO_SECRET_ACCESS_KEY']
  	  aws.availability_zone = "eu-west-1a"
  	  aws.private_ip_address = '${hadoop_master}'
  	  aws.region = 'eu-west-1'
  	  aws.security_groups = 'sg-db0dc0be'
  	  aws.subnet_id = 'subnet-4d64893a'
  	  aws.associate_public_ip = true
      aws.keypair_name = 'Lukas Test'

      aws.ami = "ami-8b6c96fc"
    
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/Users/cscarion/.ssh/LukasTest.pem"
      aws.tags = { "Name" => "Hadoop Master Box"}
    
    end
  end
  
  config.vm.define :hadoop1 do |box|
    
    box.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_DOJO_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_DOJO_SECRET_ACCESS_KEY']
  	  aws.availability_zone = "eu-west-1a"
  	  aws.private_ip_address = '${hadoop_1}'
  	  aws.region = 'eu-west-1'
  	  aws.security_groups = 'sg-db0dc0be'
  	  aws.subnet_id = 'subnet-4d64893a'
  	  aws.associate_public_ip = false
      aws.keypair_name = 'Lukas Test'

      aws.ami = "ami-8b6c96fc"
    
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/Users/cscarion/.ssh/LukasTest.pem"
      aws.tags = { "Name" => "Hadoop 1 Box"}
    
    end
  end
  
  config.vm.define :hadoop2 do |box|
    
    box.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_DOJO_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_DOJO_SECRET_ACCESS_KEY']
  	  aws.availability_zone = "eu-west-1a"
  	  aws.private_ip_address = '${hadoop_2}'
  	  aws.region = 'eu-west-1'
  	  aws.security_groups = 'sg-db0dc0be'
  	  aws.subnet_id = 'subnet-4d64893a'
  	  aws.associate_public_ip = false
      aws.keypair_name = 'Lukas Test'

      aws.ami = "ami-8b6c96fc"
    
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/Users/cscarion/.ssh/LukasTest.pem"
      aws.tags = { "Name" => "Hadoop 2 Box"}
    
    end
  end
  
  config.vm.define :hadoop3 do |box|
    
    box.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_DOJO_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_DOJO_SECRET_ACCESS_KEY']
  	  aws.availability_zone = "eu-west-1a"
  	  aws.private_ip_address = '${hadoop_3}'
  	  aws.region = 'eu-west-1'
  	  aws.security_groups = 'sg-db0dc0be'
  	  aws.subnet_id = 'subnet-4d64893a'
  	  aws.associate_public_ip = false
      aws.keypair_name = 'Lukas Test'

      aws.ami = "ami-8b6c96fc"
    
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/Users/cscarion/.ssh/LukasTest.pem"
      aws.tags = { "Name" => "Hadoop 3 Box"}
    
    end
  end
  
end